LINE_NAMES = ['L-1', 'L-2', 'L-3', 'L-4', 'L-5', 'L-6', 'L-7', 'L-8', 'L-9', 'L-10', 'L-3&4', 'AMEL']

STATIONS = [
    ('L-1', 'NEW BUS ADDA', 'NBAA'),
    ('L-1', 'HINDON RIVER', 'HDNR'),
    ('L-1', 'ARTHALA', 'ATHA'),
    ('L-1', 'MOHAN NAGAR', 'MNGM'),
    ('L-1', 'SHYAM PARK', 'SMPK'),
    ('L-1', 'RAJENDRA NAGAR', 'RJNM'),
    ('L-1', 'RAJ BAGH', 'RJBH'),
    ('L-1', 'SHAHID NAGAR', 'SHDN'),
    ('L-1', 'DILSHAD GARDEN', 'DSG'),
    ('L-1', 'JHILMIL', 'JLML'),
    ('L-1', 'MANSAROVAR PARK', 'MPK'),
    ('L-1', 'SHAHDARA', 'SHD'),
    ('L-1', 'WELCOME', 'WC'),
    ('L-1', 'SEELAMPUR', 'SLAP'),
    ('L-1', 'SHASTRI PARK', 'SHPK'),
    ('L-1', 'TISHAZARI', 'TZI'),
    ('L-1', 'PUL BANGASH', 'PBGH'),
    ('L-1', 'PRATAP NAGAR', 'PRA'),
    ('L-1', 'SHASTRI NAGAR', 'SHT'),
    ('L-1', 'KANHAIYA NAGAR', 'KN'),
    ('L-1', 'KESHAVPURAM', 'KP'),
    ('L-1', 'NETAJI SUBHASH PLACE', 'NSHP'),
    ('L-1', 'KOHAT ENCLAVE', 'KE'),
    ('L-1', 'MADHUBAN CHOWK (PITAMPURA)', 'PTP'),
    ('L-1', 'ROHINI EAST', 'RHE'),
    ('L-1', 'ROHINI WEST', 'RHW'),
    ('L-1', 'RITHALA', 'RI'),
    ('L-2', 'SAMAYPUR BADLI', 'SPBI'),
    ('L-2', 'ROHINI SECT-18', 'RISE'),
    ('L-2', 'HAIDARPUR', 'BIMR'),
    ('L-2', 'JAHANGIRPURI', 'JGPI'),
    ('L-2', 'ADARSH NAGAR', 'AHNR'),
    ('L-2', 'AZADPUR', 'AZU'),
    ('L-2', 'MODEL TOWN', 'MDTW'),
    ('L-2', 'GTB NAGAR', 'GTBR'),
    ('L-2', 'VISHWA VIDYALAYA', 'VW'),
    ('L-2', 'VIDHAN SABHA', 'VS'),
    ('L-2', 'KASHMERE GATE', 'KGR'),
    ('L-2', 'KASHMERE GATE', 'KGM'),
    ('L-2', 'CIVIL LINE', 'CL'),
    ('L-2', 'CHANDNI CHOWK', 'CHK'),
    ('L-2', 'CHAWRI BAZAR', 'CWBR'),
    ('L-2', 'NEW DELHI', 'NDI'),
    ('L-2', 'RAJIV CHOWK', 'RCK'),
    ('L-2', 'PATEL CHOWK', 'PTCK'),
    ('L-2', 'CENTRAL SECRETARIAT L-2', 'CTST'),
    ('L-2', 'CENTRAL SECRETARIAT L-6', 'CTST-N'),
    ('L-2', 'UDYOG BHAWAN', 'UDB'),
    ('L-2', 'LOK KALYAN MARG', 'RCC'),
    ('L-2', 'JOR BAGH', 'JB'),
    ('L-2', 'AIIMS', 'AIIM'),
    ('L-2', 'INA', 'INA'),
    ('L-2', 'GREEN PARK', 'GNPK'),
    ('L-2', 'MALVIYA NAGAR', 'MVNR'),
    ('L-2', 'HAUZ KHAS', 'HKS'),
    ('L-2', 'SAKET', 'SAKT'),
    ('L-2', 'QUTABMINAR', 'QM'),
    ('L-2', 'CHHATARPUR', 'CHTP'),
    ('L-2', 'SULTANPUR', 'SLTP'),
    ('L-2', 'GHITORINI', 'GTNI'),
    ('L-2', 'ARJANGARH', 'AJG'),
    ('L-2', 'GURU DRONACHARYA', 'GE'),
    ('L-2', 'SIKANDERPUR', 'SKRP'),
    ('L-2', 'MG ROAD', 'MGRO'),
    ('L-2', 'IFFCO CHOWK', 'IFOC'),
    ('L-2', 'MILLENNIUM CITY CENTRE GURUGRAM', 'HCC'),
    ('L-3&4', 'NOIDA ELECTRONIC CITY', 'NECC'),
    ('L-3&4', 'NOIDA SECTOR 62', 'SSTN'),
    ('L-3&4', 'NOIDA SECTOR 59', 'SFNN'),
    ('L-3&4', 'NOIDA SECTOR 61', 'SSON'),
    ('L-3&4', 'NOIDA SECTOR 52', 'SFTN'),
    ('L-3&4', 'NOIDA SECTOR 34', 'STFN'),
    ('L-3&4', 'NOIDA CITY CENTRE', 'NCC'),
    ('L-3&4', 'GOLF COURSE', 'GEC'),
    ('L-3&4', 'NOIDA SECTOR 18', 'NSET'),
    ('L-3&4', 'NOIDA SECTOR 16', 'NSST'),
    ('L-3&4', 'NOIDA SECTOR 15', 'NSFT'),
    ('L-3&4', 'NEW ASHOK NAGAR', 'NAKR'),
    ('L-3&4', 'MAYUR VIHAR PH. EXT.', 'MVPE'),
    ('L-3&4', 'MAYUR VIHAR PHASE I', 'MVPI'),
    ('L-3&4', 'AKSHARDHAM', 'ASDM'),
    ('L-3&4', 'VAISHALI', 'VASI'),
    ('L-3&4', 'KAUSHAMBI', 'KSHI'),
    ('L-3&4', 'ANAND VIHAR', 'AVIT'),
    ('L-3&4', 'KARKARDUMA', 'KKDA'),
    ('L-3&4', 'PREET VIHAR', 'PTVR'),
    ('L-3&4', 'NIRMAN VIHAR', 'NV'),
    ('L-3&4', 'LAXMI NAGAR', 'LN'),
    ('L-3&4', 'YAMUNA BANK', 'YB'),
    ('L-3&4', 'INDRAPRASTHA', 'IDPT'),
    ('L-3&4', 'SUPREME COURT', 'PTMD'),
    ('L-3&4', 'MANDI HOUSE (L-3)', 'MDHS'),
    ('L-3&4', 'BARAKHAMBA', 'BRKR'),
    ('L-3&4', 'RK ASHRAM MARG', 'RKAM'),
    ('L-3&4', 'JHANDEWALAN', 'JW'),
    ('L-3&4', 'KAROL BAGH', 'KB'),
    ('L-3&4', 'RAJENDRA PLACE', 'RP'),
    ('L-3&4', 'PATEL NAGAR', 'PN'),
    ('L-3&4', 'SHADIPUR', 'SP'),
    ('L-3&4', 'MOTI NAGAR', 'MN'),
    ('L-3&4', 'RAMESH NAGAR', 'RN'),
    ('L-3&4', 'RAJOURI GARDEN', 'RG'),
    ('L-3&4', 'TAGORE GARDEN', 'TG'),
    ('L-3&4', 'SUBHASH NAGAR', 'SN'),
    ('L-3&4', 'TILAK NAGAR', 'TN'),
    ('L-3&4', 'JANAKPURI EAST', 'JPE'),
    ('L-3&4', 'JANAKPURI WEST', 'JPW'),
    ('L-3&4', 'JANAKPURI WEST-8', 'JPW-8'),
    ('L-3&4', 'UTTAM NAGAR EAST', 'UNE'),
    ('L-3&4', 'UTTAM NAGAR WEST', 'UNW'),
    ('L-3&4', 'NAWADA', 'NWD'),
    ('L-3&4', 'DWARKA MOR', 'DM'),
    ('L-3&4', 'DWARKA', 'DW'),
    ('L-3&4', 'DWARKA-9', 'DW9'),
    ('L-3&4', 'DWARKA SECTOR 14', 'DSFN'),
    ('L-3&4', 'DWARKA SECTOR 13', 'DSTN'),
    ('L-3&4', 'DWARKA SECTOR 12', 'DSW'),
    ('L-3&4', 'DWARKA SECTOR 11', 'DSE'),
    ('L-3&4', 'DWARKA SECTOR 10', 'DST'),
    ('L-3&4', 'DWARKA SECTOR 9', 'DSN'),
    ('L-3&4', 'DWARKA SECTOR 8', 'DWET'),
    ('L-3&4', 'DWARKA SECTOR 21', 'DWTO'),
    ('L-5', 'INDERLOK-1', 'ILOK'),
    ('L-5', 'KIRTI NAGAR', 'KNR.'),
    ('L-5', 'INDERLOK-5', 'ILOK- N'),
    ('L-5', 'KIRTI NAGAR', 'KNR-L-5'),
    ('L-5', 'SATGURU RAMSINGH MARG', 'SRSM'),
    ('L-5', 'ASHOK PARK MAIN', 'APMN'),
    ('L-5', 'PUNJABI BAGH', 'PBGA'),
    ('L-5', 'SHIVAJI PARK', 'SHVP'),
    ('L-5', 'MADIPUR', 'MAPR'),
    ('L-5', 'PASHCHIM VIHAR EAST', 'PVE'),
    ('L-5', 'PASHCHIM VIHAR WEST', 'PVW'),
    ('L-5', 'PEERAGARHI', 'PAGI'),
    ('L-5', 'UDYOG NAGAR', 'UNRG'),
    ('L-5', 'SURAJMAL STADIUM', 'SMSM'),
    ('L-5', 'NANGLOI', 'NNOI'),
    ('L-5', 'NANGLOI RAILWAY STATION', 'NRSN'),
    ('L-5', 'RAJDHANI PARK', 'RDPK'),
    ('L-5', 'MUNDKA', 'MUDK'),
    ('L-5', 'MUNDKA INDUSTRIAL AREA', 'MIAA'),
    ('L-5', 'GHEWRA METRO STATION', 'GHEM'),
    ('L-5', 'TIKRI KALAN', 'TKLM'),
    ('L-5', 'TIKRI BORDER', 'TKBR'),
    ('L-5', 'PANDIT SHRI RAM SHARMA"', 'MIEE'),
    ('L-5', 'BAHADURGARH CITY', 'BUSS'),
    ('L-5', 'BRIG. HOSHIAR SINGH', 'CIPK'),
    ('L-6', 'MANDI HOUSE-6', 'MDHS-6'),
    ('L-6', 'KASHMERE GATE-6', 'KG-6'),
    ('L-6', 'LAL QUILA', 'LLQA'),
    ('L-6', 'JAMA MASJID', 'JAMD'),
    ('L-6', 'DELHI GATE', 'DLIG'),
    ('L-6', 'ITO', 'ITO'),
    ('L-6', 'JANPATH', 'JANP'),
    ('L-6', 'KHAN MARKET', 'KM'),
    ('L-6', 'JLN STADIUM', 'JLNS'),
    ('L-6', 'JANGPURA', 'JGPA'),
    ('L-6', 'LAJPAT NAGAR', 'LJPN'),
    ('L-6', 'MOOLCHAND', 'MLCD'),
    ('L-6', 'KAILASH COLONY', 'KHCY'),
    ('L-6', 'NEHRU PLACE', 'NP'),
    ('L-6', 'GOVINDPURI', 'GDPI'),
    ('L-6', 'OKHLA', 'OK'),
    ('L-6', 'JASOLA APOLLO', 'JLA'),
    ('L-6', 'SARITA VIHAR', 'STVR'),
    ('L-6', 'MOHAN ESTATE', 'METE'),
    ('L-6', 'TUGLAKABAD', 'TKBD'),
    ('L-6', 'BADARPUR', 'BAPU'),
    ('L-6', 'SARAI', 'SRAI'),
    ('L-6', 'NHPC CHOWK', 'NHPC'),
    ('L-6', 'MEWLA MAHARAJPUR', 'NMJR'),
    ('L-6', 'SECTOR 28', 'FTTA'),
    ('L-6', 'BADKAL MOR', 'BKMR'),
    ('L-6', 'FARIDABAD OLD', 'OFDB'),
    ('L-6', 'NEELAM CHOWK AJRONDA', 'NCAJ'),
    ('L-6', 'BATA CHOWK', 'BACH'),
    ('L-6', 'ESCORT MUJESAR', 'ECMJ'),
    ('L-6', 'SANT SURDAS SIHI', 'NCBC'),
    ('L-6', 'RAJA NAHAR SINGH (BALLAVGARH)', 'BVHM'),
    ('L-7', 'LAJPAT NAGAR-7', 'LJPN-7'),
    ('L-7', 'WELCOME', 'WC-7'),
    ('L-7', 'NETAJI SUBHASH PLACE-7', 'NSHP'),
    ('L-7', 'AZADPUR-7', 'AZU 7'),
    ('L-7', 'INA-7', 'INA-7'),
    ('L-7', 'MAYUR VIHAR PHASE I', 'MVPI'),
    ('L-7', 'ANAND VIHAR ISBT', 'AVIT-7'),
    ('L-7', 'KARKARDUMA', 'KKDA-7'),
    ('L-7', 'RAJOURI GARDEN-7', 'RG'),
    ('L-7', 'MAJLIS PARK', 'MKPR'),
    ('L-7', 'SHALIMAR BAGH', 'SMBG'),
    ('L-7', 'SHAKURPUR', 'SAKP'),
    ('L-7', 'PUNJABI BAGH WEST', 'PBGW'),
    ('L-7', 'ESI HOSPITAL', 'ESIH'),
    ('L-7', 'MAYAPURI', 'MYPI'),
    ('L-7', 'NARAINA VIHAR', 'NAVR'),
    ('L-7', 'DELHI CANT', 'DLIC'),
    ('L-7', 'DURGABAI DESHMUKH SOUTH CAMPUS', 'DDSC'),
    ('L-7', 'SIR VISHWESHARAI AH MOTI BAGH', 'SVMB'),
    ('L-7', 'BHIKAJI CAMA PLACE', 'BKCP'),
    ('L-7', 'SAROJINI NAGAR MARKET', 'SOJI'),
    ('L-7', 'SOUTH EXTENSION', 'SOEN'),
    ('L-7', 'VINOBA PURI', 'VNPR'),
    ('L-7', 'ASSHRAM', 'AHRM'),
    ('L-7', 'SRAI KALE KHAN NIZAMUDDIN', 'NIZM'),
    ('L-7', 'MAYUR VIHAR POCKET-I', 'MVPO'),
    ('L-7', 'TRILOKPURI', 'TKPR'),
    ('L-7', 'VINOD NAGAR EAST MAYUR VIHAR II', 'VENT'),
    ('L-7', 'MANDAWALI-WEST VINOD NAGAR', 'VNNR'),
    ('L-7', 'IP EXTENSION', 'IPE'),
    ('L-7', 'KARKARDUMA COURT', 'KKDC'),
    ('L-7', 'KIRSHNA NAGAR', 'KHNA'),
    ('L-7', 'EAST AZAD NAGAR', 'EANR'),
    ('L-7', 'JAFFRABAD', 'JFRB'),
    ('L-7', 'MAUJPUR', 'MUPR'),
    ('L-7', 'GOKULPURI', 'GKPR'),
    ('L-7', 'JOHRI ENCLAVE', 'JIEE'),
    ('L-7', 'SHIV VIHAR', 'SVVR'),
    ('L-8', 'HAUZKHAS', 'HKS-8'),
    ('L-8', 'BOTANICAL GARDEN-8', 'BCGN-8'),
    ('L-8', 'BOTANICAL GARDEN', 'BCGN'),
    ('L-8', 'OKHLA BIRD CENTURY', 'OBC'),
    ('L-8', 'KALINDI KUNJ', 'KIKJ'),
    ('L-8', 'JASOLA VIHAR', 'JLA-8'),
    ('L-8', 'OKHLA VIHAR', 'OVA'),
    ('L-8', 'JAMIA MILIA ISLAMIA', 'JANR'),
    ('L-8', 'SUKHDEV VIHAR', 'IWNR'),
    ('L-8', 'OKHLA NSIC', 'OKNS'),
    ('L-8', 'KALKAJI MANDIR-8', 'KJMD-8'),
    ('L-8', 'KALKAJI MANDIR', 'KJMD'),
    ('L-8', 'NEHRU ENCLAVE', 'NUEE'),
    ('L-8', 'GREATER KAILASH', 'GKEI'),
    ('L-8', 'CHIRAG DELHI', 'CDLI'),
    ('L-8', 'PANCHSHEEL PARK', 'PSPK'),
    ('L-8', 'IIT', 'IIT'),
    ('L-8', 'R K PURAM', 'RKPM'),
    ('L-8', 'MUNIRKA', 'MIRK'),
    ('L-8', 'VASANT VIHAR', 'VTVR'),
    ('L-8', 'SHANKAR VIHAR', ''),
    ('L-8', 'IGDA', 'IGDA'),
    ('L-8', 'SADAR BAZAR', 'SABR'),
    ('L-8', 'PALAM', 'PALM'),
    ('L-8', 'DASHRATPURI', 'DSHP'),
    ('L-8', 'DABRI MOR', 'DBMR'),
    ('L-9', 'NANGALI', 'NNGI'),
    ('L-9', 'DHANSA BUSS STAND', 'DNBT'),
    ('L-9', 'NAJAFGARH', 'NFGH'),
    ('AMEL', 'NEW DELHI (AMEL)', 'NDRU'),
    ('AMEL', 'SHIWAJI STADIUM', 'SJSU'),
    ('AMEL', 'DHAULA KUAN', 'DKV'),
    ('AMEL', 'DELHI AEROCITY', 'DACY'),
    ('AMEL', 'IGI AIRPORT', 'APOT'),
    ('AMEL', 'DWARKA 21 (AMEL)', 'DSTO'),
    ('AMEL', 'IICC YASHOBHOOMI', 'IICC'),
]
